### ISSUE TITLE
This App is not loading on windows

### ISSUE THREAD

**Issue by kushal-0802** [GendelfLugansk/ember-file-uploader#1]
Hello! I have downloaded your app and  i have performed all the steps mentioned. but the App is not loading in the browser, i am just getting White screen. I am running windows 7 64Bit. 
Am i missing thing here? 

Thank you

**Comment by GendelfLugansk** [comment]
I tried to re-install app and it doesn't work on Ubuntu too. From what I see in dev console, it's this issue http://stackoverflow.com/questions/34702284/getting-uncaught-error-assertion-failed-ember-views-require-jquery-between-1
Trying to update dependencies now.

**Comment by GendelfLugansk** [comment]
Check latest version please (don't forget to do npm install && bower install). It should work now. At least it works for me (again). 

It would be great to upgrade this demo to ember 2.x, but unfortunately I don't have time for this.

**Comment by kushal-0802** [comment]
hello! i have uninstalled ember, and reinstalled it, i have also performed the following
npm cache clean
bower cache clean
npm install
bower install 

but still, nothing seems to be happening. when ever i load http://localhost:4200 on my browser only white screen appears. is there any separate dependencies or addons for windows alone?

**Comment by GendelfLugansk** [comment]
Did you checkout latest version? What do you see in dev tools?

**Comment by kushal-0802** [comment]
Is it the latest version of the app? sorry sir i did not catch that. 
i have the following versions:
node: 6.9.4
npm: 2.13.4
ember : 1.13.8

**Comment by kushal-0802** [comment]
Sir, when i do npm install i am getting the following error on the command line:
> bufferutil@1.1.0 install C:\Users\HTL_KUSHAL\Vinaya\ember-file-uploader-master
\node_modules\bufferutil
> node-gyp rebuild


C:\Users\HTL_KUSHAL\Vinaya\ember-file-uploader-master\node_modules\bufferutil>if
 not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm
\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else
(node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\nod
e_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\configure.js:404:11
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\grac
eful-fs\polyfills.js:264:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\HTL_KUSHAL\Vinaya\ember-file-uploader-master\node_modules\
bufferutil
gyp ERR! node -v v6.9.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

> utf-8-validate@1.1.0 install C:\Users\HTL_KUSHAL\Vinaya\ember-file-uploader-ma
ster\node_modules\utf-8-validate
> node-gyp rebuild


C:\Users\HTL_KUSHAL\Vinaya\ember-file-uploader-master\node_modules\utf-8-validat
e>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules
\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  e
lse (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\nod
e_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\configure.js:404:11
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\grac
eful-fs\polyfills.js:264:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\HTL_KUSHAL\Vinaya\ember-file-uploader-master\node_modules\
utf-8-validate
gyp ERR! node -v v6.9.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

**Comment by kushal-0802** [comment]
now performing the following: 
npm install -g ember-cli@2.11.0-beta.1

i am following the steps mentioned in this link:
https://github.com/ember-cli/ember-cli/releases

**Comment by rupdegraff** [comment]
I am able to open the app without problems using Windows 8.1 Enterprise and Node v4.5.0.

**Comment by GendelfLugansk** [comment]
@kushal-0802 that errors most probably connected with node/ember-cli versions. But if ``ember s`` works, app should work too.
